version: "3.9"
services:
  nginx:
    build: nginx/.
    ports: 
      - 8081:8081
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d
  httpd:
    build: httpd/.
    ports: 
      - 8082:8082
    volumes:
      - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf

